#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-base

if [ "$1" = "-h" ]; then
    echo "writes a csv dump for servald pidstat properties to $MONITOR_PATH"
    exit 0
fi

# using latest monitoring path
MONITOR_PATH=`ls -td -- $MONITOR_PATH/*/ | grep 20 | head -n 1`
OUTFILE_SERVAL=$(echo "$MONITOR_PATH/pidstat/serval-pidstat-$(hostname).csv" | sed s#//*#/#g)
OUTFILE_RPC=$(echo "$MONITOR_PATH/pidstat/rpc-pidstat-$(hostname).csv" | sed s#//*#/#g)

pidstat -druh -p ALL | sed '1d;/^$/d;s/#[ ]*Time/timestamp/g;s/^[ ]*//;s/[ ]\+/,/g' | head -n 1 > $OUTFILE_SERVAL
pidstat -druh -p ALL | sed '1d;/^$/d;s/#[ ]*Time/timestamp/g;s/^[ ]*//;s/[ ]\+/,/g' | head -n 1 > $OUTFILE_RPC

#while [ true ]; do
#    sleep $SLEEP_TIME

    nohup pidstat -druh -p $SERVAL_PID 1 | sed '1d;/^[#]/d;/^$/d;s/^[ ]*//;s/[ ]\+/,/g' >> $OUTFILE_SERVAL &
    nohup pidstat -druh -C "rpc" 1 | sed '1d;/^[#]/d;/^$/d;s/^[ ]*//;s/[ ]\+/,/g' >> $OUTFILE_RPC &

#done
